version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    environment:
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
      TZ: America/Santiago
      # DISABLE_JEMALLOC: true
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyBT0:/dev/ttyBT0
    # Not define ports because used to host network
    # ports:
    #   - "8123:8123"
    restart: unless-stopped
    privileged: true
    network_mode: host